name: 修补boot

on:
  workflow_dispatch:
    inputs:
      boot_url:
        description: 'boot 下载直链'
        required: true
        default: ''

jobs:
  BootIMGExtractAction:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt install aria2 -y
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV

      - name: 提取镜像
        run: |
          cd ~
          git clone https://github.com/jax0ncai/Magisk_patche.git Magisk
          cd Magisk
          aria2c -s 10 -x 10 -d . -o boot.img "${{ github.event.inputs.boot_url }}"
          ./boot.sh
          cd ${{ github.workspace }}
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "boot 下载直链：${{ github.event.inputs.boot_url }}" >> info.md
      - name: 上传镜像
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/Magisk/done/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}"
            token: ${{ secrets.GITHUB_TOKEN }}